### PR TITLE
Feature/184416011 update rollup version

### PR DESCRIPTION
**Pull request by jeremymccurdy-redspace**
This PR updates Rollup to the latest version, and updates the rollup plugins to their latest versions (they all have new NPM packages).

Note: Added .nvmrc file to set Node version at the latest LTS (18.15.0), Rollup needs a minimum of 14.18.0.

Ticket: https://www.pivotaltracker.com/story/show/184416011

### CODE REVIEW

**Review by selenaqian — APPROVED** [review]

**Comment by selenaqian** [comment]
Code looks fine and I can run the build locally, but looks like the GHA builds are failing. Do we need to update the build actions since there's a minimum for the node version with the updated rollup version??

**Review by selenaqian — CHANGES_REQUESTED** [review]
Code looks fine and I can run the build locally, but looks like the GHA builds are failing. Do we need to update the actions since there's a minimum for the node version with the updated rollup version?

**Comment by deycorinne** [comment]
I think you will need to update the node version matrix [here](https://github.com/SpringRoll/Bellhop/blob/main/.github/workflows/nodejs.yml#L16) as well

**Comment by deycorinne** [comment]
Ooh and [here](https://github.com/SpringRoll/Bellhop/blob/main/.github/workflows/npm-deploy.yml#L14)

**Review by deycorinne — CHANGES_REQUESTED** [review]
Update actions please!

**Comment by jeremymccurdy-redspace** [comment]
I've updated the actions. It now checks for Node 16.x and 18.x. There were still errors with Babel CLI on Node 14, but 16 and up build correctly.

**Review by selenaqian — APPROVED** [review]

**Review by deycorinne — APPROVED** [review]

**Pull request merged**
